import { randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { config } from './shared/config.js';
import { toApiError } from './shared/errors.js';
import { logger } from './shared/logging.js';
import { REQUEST_ID_HEADER } from './shared/request-id.js';
import { checkDatabase, disconnectDatabase } from './infrastructure/database/client.js';
import { authenticate, login, logout, me, refresh, register } from './modules/auth.js';
import { addMember, createWorkspace, getWorkspace, listMembers, listWorkspaces, removeMember, requestBody, updateMember, updateWorkspace } from './modules/workspaces.js';
import { createProduct, createVariant, deleteProduct, deleteVariant, getProduct, listProducts, updateProduct, updateVariant } from './modules/products.js';
import { addAsset, addCopy, createCreative, deleteCreative, getCreative, listCreatives, updateCreative } from './modules/creatives.js';
import { runAITask } from './modules/ai.js';
import { createAudience, deleteAudience, getAudience, listAudiences, updateAudience } from './modules/audiences.js';
import { createAd, createAdSet, createCampaign, deleteAd, deleteAdSet, deleteCampaign, getCampaign, listAds, listAdSets, listCampaigns, updateAd, updateAdSet, updateCampaign } from './modules/campaigns.js';
import { detectCreativeFatigue, diagnoseCampaign, getCampaignAnalytics, ingestPerformanceSnapshot, listCreativeFatigue, listDiagnostics } from './modules/analytics.js';
import { createCustomer, createOrder, createOrGetShipment, getOrder, getProfitDashboard, listCustomers, listOrders, recordAttribution, updateOrderStatus, updateShipment } from './modules/orders.js';
import { beginMetaOAuth, completeMetaOAuth, createMetaDraft, discoverMetaAccounts, getMetaConnection, mutateMetaCampaign, syncMetaAdSets, syncMetaAds, syncMetaCampaigns, syncMetaInsights } from './modules/meta.js';
import { createAgentRun, createAutomationRule, decideAgentApproval, executeAgentRun, getAgentRun, listAutomationRules, setAutomationRule } from './modules/agent.js';

function writeJson(response: ServerResponse, status: number, body: unknown, requestId: string): void { response.statusCode = status; response.setHeader('content-type', 'application/json; charset=utf-8'); response.setHeader(REQUEST_ID_HEADER, requestId); if (status === 204) { response.end(); return; } response.end(JSON.stringify(body)); }
function requestIdFrom(request: IncomingMessage): string { const supplied = request.headers[REQUEST_ID_HEADER]; return (Array.isArray(supplied) ? supplied[0] : supplied)?.trim() || randomUUID(); }

async function handle(request: IncomingMessage, response: ServerResponse): Promise<void> {
  const requestId = requestIdFrom(request); const url = new URL(request.url ?? '/', `http://${request.headers.host ?? 'localhost'}`); const path = url.pathname;
  try {
    if (request.method === 'GET' && path === '/api/v1/health') { const databaseUp = await checkDatabase(); writeJson(response, databaseUp ? 200 : 503, { status: databaseUp ? 'ok' : 'degraded', service: 'adsgenius-api', version: config.appVersion, database: databaseUp ? 'up' : 'down', requestId }, requestId); return; }
    if (request.method === 'POST' && path === '/api/v1/auth/register') { writeJson(response, 201, await register(await requestBody(request), response, requestId), requestId); return; }
    if (request.method === 'POST' && path === '/api/v1/auth/login') { writeJson(response, 200, await login(await requestBody(request), response, requestId), requestId); return; }
    if (request.method === 'POST' && path === '/api/v1/auth/refresh') { writeJson(response, 200, await refresh(request, response, requestId), requestId); return; }
    if (request.method === 'POST' && path === '/api/v1/auth/logout') { await logout(request, response, requestId); writeJson(response, 200, { ok: true }, requestId); return; }
    if (request.method === 'GET' && path === '/api/v1/auth/me') { writeJson(response, 200, await me(request), requestId); return; }
    if (request.method === 'GET' && path === '/api/v1/meta/oauth/callback') { writeJson(response, 200, await completeMetaOAuth(request, requestId), requestId); return; }
    const auth = await authenticate(request);
    if (request.method === 'GET' && path === '/api/v1/workspaces') { writeJson(response, 200, { data: await listWorkspaces(auth) }, requestId); return; }
    if (request.method === 'POST' && path === '/api/v1/workspaces') { writeJson(response, 201, await createWorkspace(auth, await requestBody(request), requestId), requestId); return; }
    const workspaceMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)$/); if (workspaceMatch) { const workspaceId = workspaceMatch[1]; if (request.method === 'GET') writeJson(response, 200, await getWorkspace(auth, workspaceId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateWorkspace(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const membersMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/members$/); if (membersMatch) { const workspaceId = membersMatch[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listMembers(auth, workspaceId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await addMember(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const memberMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/members\/([^/]+)$/); if (memberMatch) { const workspaceId = memberMatch[1]; const memberId = memberMatch[2]; if (request.method === 'PATCH') writeJson(response, 200, await updateMember(auth, workspaceId, memberId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await removeMember(auth, workspaceId, memberId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaOAuth = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/oauth$/); if (metaOAuth) { if (request.method === 'POST') writeJson(response, 200, await beginMetaOAuth(auth, metaOAuth[1]), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaConnection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/connection$/); if (metaConnection) { if (request.method === 'GET') writeJson(response, 200, await getMetaConnection(auth, metaConnection[1]), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaAccounts = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/accounts$/); if (metaAccounts) { if (request.method === 'POST') writeJson(response, 200, await discoverMetaAccounts(auth, metaAccounts[1], requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaCampaignSync = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/accounts\/([^/]+)\/campaigns\/sync$/); if (metaCampaignSync) { if (request.method === 'POST') writeJson(response, 200, await syncMetaCampaigns(auth, metaCampaignSync[1], metaCampaignSync[2], requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaAdSetSync = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/campaigns\/([^/]+)\/adsets\/sync$/); if (metaAdSetSync) { if (request.method === 'POST') writeJson(response, 200, await syncMetaAdSets(auth, metaAdSetSync[1], metaAdSetSync[2], requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaAdSync = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/adsets\/([^/]+)\/ads\/sync$/); if (metaAdSync) { if (request.method === 'POST') writeJson(response, 200, await syncMetaAds(auth, metaAdSync[1], metaAdSync[2], requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaInsights = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/campaigns\/([^/]+)\/insights$/); if (metaInsights) { if (request.method === 'POST') { const body = await requestBody(request); writeJson(response, 200, await syncMetaInsights(auth, metaInsights[1], metaInsights[2], String(body.start ?? ''), String(body.end ?? ''), requestId), requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaDraft = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/campaigns\/draft$/); if (metaDraft) { if (request.method === 'POST') writeJson(response, 201, await createMetaDraft(auth, metaDraft[1], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const metaMutation = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/meta\/campaigns\/([^/]+)\/mutation$/); if (metaMutation) { if (request.method === 'POST') writeJson(response, 200, await mutateMetaCampaign(auth, metaMutation[1], metaMutation[2], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const agentRunCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/agent\/runs$/); if (agentRunCollection) { const workspaceId = agentRunCollection[1]; if (request.method === 'POST') writeJson(response, 201, await createAgentRun(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const agentRunMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/agent\/runs\/([^/]+)$/); if (agentRunMatch) { const workspaceId = agentRunMatch[1]; const runId = agentRunMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getAgentRun(auth, workspaceId, runId), requestId); else if (request.method === 'POST') writeJson(response, 200, await executeAgentRun(auth, workspaceId, runId, requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const agentApproval = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/agent\/runs\/([^/]+)\/approval$/); if (agentApproval) { if (request.method === 'POST') { const body = await requestBody(request); writeJson(response, 200, await decideAgentApproval(auth, agentApproval[1], agentApproval[2], body.approved === true, typeof body.note === 'string' ? body.note : undefined, requestId), requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const automationCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/agent\/automation$/); if (automationCollection) { const workspaceId = automationCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listAutomationRules(auth, workspaceId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createAutomationRule(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const automationMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/agent\/automation\/([^/]+)$/); if (automationMatch) { if (request.method === 'PATCH') { const body = await requestBody(request); writeJson(response, 200, await setAutomationRule(auth, automationMatch[1], automationMatch[2], body.enabled === true, requestId), requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const productsCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/products$/); if (productsCollection) { const workspaceId = productsCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listProducts(auth, workspaceId, url.searchParams.get('search') ?? undefined) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createProduct(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const productMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/products\/([^/]+)$/); if (productMatch) { const workspaceId = productMatch[1]; const productId = productMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getProduct(auth, workspaceId, productId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateProduct(auth, workspaceId, productId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteProduct(auth, workspaceId, productId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const variantsMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/products\/([^/]+)\/variants$/); if (variantsMatch) { const workspaceId = variantsMatch[1]; const productId = variantsMatch[2]; if (request.method === 'POST') writeJson(response, 201, await createVariant(auth, workspaceId, productId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const variantMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/products\/([^/]+)\/variants\/([^/]+)$/); if (variantMatch) { const workspaceId = variantMatch[1]; const productId = variantMatch[2]; const variantId = variantMatch[3]; if (request.method === 'PATCH') writeJson(response, 200, await updateVariant(auth, workspaceId, productId, variantId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteVariant(auth, workspaceId, productId, variantId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const creativesCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/creatives$/); if (creativesCollection) { const workspaceId = creativesCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listCreatives(auth, workspaceId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createCreative(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const creativeMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/creatives\/([^/]+)$/); if (creativeMatch) { const workspaceId = creativeMatch[1]; const creativeId = creativeMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getCreative(auth, workspaceId, creativeId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateCreative(auth, workspaceId, creativeId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteCreative(auth, workspaceId, creativeId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const copyMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/creatives\/([^/]+)\/copies$/); if (copyMatch) { if (request.method === 'POST') writeJson(response, 201, await addCopy(auth, copyMatch[1], copyMatch[2], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const assetMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/creatives\/([^/]+)\/assets$/); if (assetMatch) { if (request.method === 'POST') writeJson(response, 201, await addAsset(auth, assetMatch[1], assetMatch[2], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const audiencesCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/audiences$/); if (audiencesCollection) { const workspaceId = audiencesCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listAudiences(auth, workspaceId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createAudience(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const audienceMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/audiences\/([^/]+)$/); if (audienceMatch) { const workspaceId = audienceMatch[1]; const audienceId = audienceMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getAudience(auth, workspaceId, audienceId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateAudience(auth, workspaceId, audienceId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteAudience(auth, workspaceId, audienceId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const campaignsCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns$/); if (campaignsCollection) { const workspaceId = campaignsCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listCampaigns(auth, workspaceId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createCampaign(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const campaignMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns\/([^/]+)$/); if (campaignMatch) { const workspaceId = campaignMatch[1]; const campaignId = campaignMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getCampaign(auth, workspaceId, campaignId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateCampaign(auth, workspaceId, campaignId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteCampaign(auth, workspaceId, campaignId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const adSetsCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns\/([^/]+)\/adsets$/); if (adSetsCollection) { const workspaceId = adSetsCollection[1]; const campaignId = adSetsCollection[2]; if (request.method === 'GET') writeJson(response, 200, { data: await listAdSets(auth, workspaceId, campaignId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createAdSet(auth, workspaceId, campaignId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const adSetMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns\/([^/]+)\/adsets\/([^/]+)$/); if (adSetMatch) { const workspaceId = adSetMatch[1]; const campaignId = adSetMatch[2]; const adSetId = adSetMatch[3]; if (request.method === 'PATCH') writeJson(response, 200, await updateAdSet(auth, workspaceId, campaignId, adSetId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteAdSet(auth, workspaceId, campaignId, adSetId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const adsCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns\/([^/]+)\/adsets\/([^/]+)\/ads$/); if (adsCollection) { const workspaceId = adsCollection[1]; const campaignId = adsCollection[2]; const adSetId = adsCollection[3]; if (request.method === 'GET') writeJson(response, 200, { data: await listAds(auth, workspaceId, campaignId, adSetId) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createAd(auth, workspaceId, campaignId, adSetId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const adMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/campaigns\/([^/]+)\/adsets\/([^/]+)\/ads\/([^/]+)$/); if (adMatch) { const workspaceId = adMatch[1]; const campaignId = adMatch[2]; const adSetId = adMatch[3]; const adId = adMatch[4]; if (request.method === 'PATCH') writeJson(response, 200, await updateAd(auth, workspaceId, campaignId, adSetId, adId, await requestBody(request), requestId), requestId); else if (request.method === 'DELETE') { await deleteAd(auth, workspaceId, campaignId, adSetId, adId, requestId); writeJson(response, 204, null, requestId); } else throw new Error('ROUTE_NOT_FOUND'); return; }
    const customerCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/customers$/); if (customerCollection) { const workspaceId = customerCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listCustomers(auth, workspaceId, url.searchParams.get('search') ?? undefined) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createCustomer(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const orderCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/orders$/); if (orderCollection) { const workspaceId = orderCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listOrders(auth, workspaceId, url.searchParams.get('status') ?? undefined) }, requestId); else if (request.method === 'POST') writeJson(response, 201, await createOrder(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const orderMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/orders\/([^/]+)$/); if (orderMatch) { const workspaceId = orderMatch[1]; const orderId = orderMatch[2]; if (request.method === 'GET') writeJson(response, 200, await getOrder(auth, workspaceId, orderId), requestId); else if (request.method === 'PATCH') writeJson(response, 200, await updateOrderStatus(auth, workspaceId, orderId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const shipmentCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/orders\/([^/]+)\/shipment$/); if (shipmentCollection) { const workspaceId = shipmentCollection[1]; const orderId = shipmentCollection[2]; if (request.method === 'POST') writeJson(response, 201, await createOrGetShipment(auth, workspaceId, orderId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const shipmentMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/shipments\/([^/]+)$/); if (shipmentMatch) { if (request.method === 'PATCH') writeJson(response, 200, await updateShipment(auth, shipmentMatch[1], shipmentMatch[2], await requestBody(request), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const attributionMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/orders\/([^/]+)\/attribution$/); if (attributionMatch) { if (request.method === 'POST') writeJson(response, 201, await recordAttribution(auth, attributionMatch[1], attributionMatch[2], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const profitDashboard = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/profit$/); if (profitDashboard) { if (request.method === 'GET') writeJson(response, 200, await getProfitDashboard(auth, profitDashboard[1], url.searchParams.get('start') ?? undefined, url.searchParams.get('end') ?? undefined), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const analyticsSnapshots = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/snapshots$/); if (analyticsSnapshots) { const workspaceId = analyticsSnapshots[1]; if (request.method === 'POST') writeJson(response, 201, await ingestPerformanceSnapshot(auth, workspaceId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const analyticsCampaign = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/campaigns\/([^/]+)$/); if (analyticsCampaign) { const workspaceId = analyticsCampaign[1]; const campaignId = analyticsCampaign[2]; if (request.method === 'GET') writeJson(response, 200, await getCampaignAnalytics(auth, workspaceId, campaignId, url.searchParams.get('start') ?? undefined, url.searchParams.get('end') ?? undefined), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const analyticsDiagnosis = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/campaigns\/([^/]+)\/diagnose$/); if (analyticsDiagnosis) { const workspaceId = analyticsDiagnosis[1]; const campaignId = analyticsDiagnosis[2]; if (request.method === 'POST') writeJson(response, 201, await diagnoseCampaign(auth, workspaceId, campaignId, await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const analyticsDiagnostics = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/diagnostics$/); if (analyticsDiagnostics) { const workspaceId = analyticsDiagnostics[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listDiagnostics(auth, workspaceId, url.searchParams.get('campaignId') ?? undefined) }, requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const fatigueCollection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/creative-fatigue$/); if (fatigueCollection) { const workspaceId = fatigueCollection[1]; if (request.method === 'GET') writeJson(response, 200, { data: await listCreativeFatigue(auth, workspaceId) }, requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const fatigueDetection = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/analytics\/creative-fatigue\/([^/]+)$/); if (fatigueDetection) { const workspaceId = fatigueDetection[1]; const creativeVersionId = fatigueDetection[2]; if (request.method === 'POST') writeJson(response, 201, await detectCreativeFatigue(auth, workspaceId, creativeVersionId, requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    const aiMatch = path.match(/^\/api\/v1\/workspaces\/([^/]+)\/ai\/tasks$/); if (aiMatch) { if (request.method === 'POST') writeJson(response, 201, await runAITask(auth, aiMatch[1], await requestBody(request), requestId), requestId); else throw new Error('ROUTE_NOT_FOUND'); return; }
    writeJson(response, 404, { error: { code: 'NOT_FOUND', message: 'Route not found.', requestId } }, requestId);
  } catch (error) {
    const apiError = toApiError(error instanceof Error && error.message === 'ROUTE_NOT_FOUND' ? new Error('Route not found.') : error, requestId);
    if (error instanceof Error && error.message === 'ROUTE_NOT_FOUND') writeJson(response, 404, { error: { code: 'NOT_FOUND', message: 'Route not found.', requestId } }, requestId); else { logger.error('Request failed', { requestId, error: error instanceof Error ? error.message : String(error) }); writeJson(response, apiError.status, apiError.body, requestId); }
  }
}

const server = createServer((request, response) => { void handle(request, response); });
server.listen(config.port, config.host, async () => { const databaseUp = await checkDatabase(); logger.info('AdsGenius API started', { host: config.host, port: config.port, database: databaseUp ? 'up' : 'down' }); if (!databaseUp && process.env.API_REQUIRE_DATABASE === 'true') { logger.error('Database is required but unavailable; shutting down.'); server.close(); await disconnectDatabase(); process.exitCode = 1; } });
async function shutdown(signal: string): Promise<void> { logger.info('Shutdown requested', { signal }); server.close(async () => { await disconnectDatabase(); }); }
process.once('SIGINT', () => void shutdown('SIGINT')); process.once('SIGTERM', () => void shutdown('SIGTERM'));
