import { randomUUID } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../infrastructure/database/client.js';
import { AppError } from '../shared/errors.js';
import type { AuthContext } from './auth.js';
import { requireWorkspaceAccess } from './workspaces.js';
import { createMetaDraft, mutateMetaCampaign } from './meta.js';

type Permission = 'ANALYZE' | 'RECOMMEND' | 'DRAFT' | 'EXECUTE' | 'AUTOMATE';
type ActionStatus = 'PREVIEW' | 'APPROVED' | 'EXECUTING' | 'SUCCEEDED' | 'FAILED' | 'REJECTED';
const rank: Record<Permission, number> = { ANALYZE: 0, RECOMMEND: 1, DRAFT: 2, EXECUTE: 3, AUTOMATE: 4 };
const validPermissions = new Set(Object.keys(rank));
const allowedTools = new Set(['ANALYTICS', 'CREATIVE', 'META']);

function permission(value: unknown, fallback: Permission = 'RECOMMEND'): Permission { const normalized = String(value ?? fallback).toUpperCase() as Permission; if (!validPermissions.has(normalized)) throw new AppError('VALIDATION_ERROR', 'Invalid agent permission level.', 400); return normalized; }
function json(value: unknown): Prisma.Sql { return Prisma.sql`${JSON.stringify(value ?? {})}::jsonb`; }
function text(value: unknown, field: string): string { if (typeof value !== 'string' || !value.trim()) throw new AppError('VALIDATION_ERROR', `${field} is required.`, 400); return value.trim(); }
async function access(auth: AuthContext, workspaceId: string) { return requireWorkspaceAccess(auth, workspaceId); }
function assertTool(tool: string) { if (!allowedTools.has(tool)) throw new AppError('VALIDATION_ERROR', `Agent tool is not allowed: ${tool}.`, 400); }
function assertActionPermission(actionPermission: Permission, configured: Permission) { if (rank[actionPermission] > rank[configured]) throw new AppError('FORBIDDEN', `Action requires ${actionPermission} permission but the configured level is ${configured}.`, 403); }
function needsApproval(level: Permission) { return rank[level] >= rank.EXECUTE; }

export async function createAgentRun(auth: AuthContext, workspaceId: string, input: Record<string, unknown>, requestId: string) {
  await access(auth, workspaceId); const goal = text(input.goal, 'goal'); const configured = permission(input.permissionLevel, 'RECOMMEND'); const rawActions = Array.isArray(input.actions) ? input.actions : [];
  const actions = rawActions.map((raw, index) => { if (!raw || typeof raw !== 'object') throw new AppError('VALIDATION_ERROR', `actions[${index}] must be an object.`, 400); const item = raw as Record<string, unknown>; const tool = text(item.tool, `actions[${index}].tool`).toUpperCase(); const action = text(item.action, `actions[${index}].action`).toUpperCase(); assertTool(tool); const level = permission(item.permissionLevel, configured); assertActionPermission(level, configured); return { tool, action, permissionLevel: level, targetId: typeof item.targetId === 'string' ? item.targetId : null, input: item.input ?? {} }; });
  const runId = randomUUID(); const now = new Date(); const plan = { goal, permissionLevel: configured, actions: actions.map((item) => ({ ...item, approvalRequired: needsApproval(item.permissionLevel), preview: { tool: item.tool, action: item.action, targetId: item.targetId, input: item.input } })) };
  await prisma.$executeRaw(Prisma.sql`INSERT INTO agent_runs (id, workspace_id, user_id, permission_level, status, goal, input_json, plan_json, created_at, updated_at) VALUES (${runId}, ${workspaceId}, ${auth.userId}, ${configured}, ${needsApproval(configured) ? 'AWAITING_APPROVAL' : 'PLANNED'}, ${goal}, ${json(input)}, ${json(plan)}, ${now}, ${now})`);
  for (const item of actions) { const actionId = randomUUID(); await prisma.$executeRaw(Prisma.sql`INSERT INTO agent_actions (id, workspace_id, run_id, tool, action, permission_level, status, input_json, preview_json, created_at) VALUES (${actionId}, ${workspaceId}, ${runId}, ${item.tool}, ${item.action}, ${item.permissionLevel}, ${needsApproval(item.permissionLevel) ? 'PREVIEW' : 'APPROVED'}, ${json(item.input)}, ${json({ tool: item.tool, action: item.action, targetId: item.targetId, input: item.input, approvalRequired: needsApproval(item.permissionLevel) })}, ${now})`); }
  if (needsApproval(configured)) { const approvalId = randomUUID(); await prisma.$executeRaw(Prisma.sql`INSERT INTO agent_approvals (id, workspace_id, run_id, requested_by, status, permission_level, expires_at, created_at) VALUES (${approvalId}, ${workspaceId}, ${runId}, ${auth.userId}, 'PENDING', ${configured}, ${new Date(Date.now() + 30 * 60 * 1000)}, ${now})`); }
  await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'agent.run.created', entityType: 'AgentRun', entityId: runId, afterJson: { permissionLevel: configured, actionCount: actions.length }, requestReference: requestId } });
  return { id: runId, status: needsApproval(configured) ? 'AWAITING_APPROVAL' : 'PLANNED', permissionLevel: configured, goal, plan };
}

export async function getAgentRun(auth: AuthContext, workspaceId: string, runId: string) { await access(auth, workspaceId); const runs = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM agent_runs WHERE id = ${runId} AND workspace_id = ${workspaceId} LIMIT 1`); if (!runs[0]) throw new AppError('NOT_FOUND', 'Agent run not found.', 404); const actions = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, tool, action, permission_level AS "permissionLevel", status, input_json AS input, preview_json AS preview, result_json AS result, rollback_json AS rollback, error_message AS "errorMessage", created_at AS "createdAt", executed_at AS "executedAt" FROM agent_actions WHERE run_id = ${runId} AND workspace_id = ${workspaceId} ORDER BY created_at ASC`); const approvals = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, status, permission_level AS "permissionLevel", requested_by AS "requestedBy", approved_by AS "approvedBy", expires_at AS "expiresAt", decision_note AS "decisionNote", created_at AS "createdAt", decided_at AS "decidedAt" FROM agent_approvals WHERE run_id = ${runId} AND workspace_id = ${workspaceId} ORDER BY created_at DESC`); return { ...runs[0], actions, approvals }; }

export async function decideAgentApproval(auth: AuthContext, workspaceId: string, runId: string, approved: boolean, note: string | undefined, requestId: string) { const membership = await access(auth, workspaceId); if (!['OWNER', 'ADMIN'].includes(membership.role)) throw new AppError('FORBIDDEN', 'Only workspace owners or admins can approve agent actions.', 403); const rows = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, status, expires_at, permission_level FROM agent_approvals WHERE run_id = ${runId} AND workspace_id = ${workspaceId} ORDER BY created_at DESC LIMIT 1`); const approval = rows[0]; if (!approval) throw new AppError('NOT_FOUND', 'Approval request not found.', 404); if (approval.status !== 'PENDING') throw new AppError('CONFLICT', 'Approval is no longer pending.', 409); if (approval.expires_at && new Date(approval.expires_at).getTime() <= Date.now()) throw new AppError('CONFLICT', 'Approval request has expired.', 409); const status = approved ? 'APPROVED' : 'REJECTED'; await prisma.$executeRaw(Prisma.sql`UPDATE agent_approvals SET status = ${status}, approved_by = ${auth.userId}, decision_note = ${note ?? null}, decided_at = NOW() WHERE id = ${approval.id}`); await prisma.$executeRaw(Prisma.sql`UPDATE agent_actions SET status = ${approved ? 'APPROVED' : 'REJECTED'}, approval_id = ${approval.id} WHERE run_id = ${runId} AND status = 'PREVIEW'`); await prisma.$executeRaw(Prisma.sql`UPDATE agent_runs SET status = ${approved ? 'APPROVED' : 'REJECTED'}, updated_at = NOW() WHERE id = ${runId} AND workspace_id = ${workspaceId}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: approved ? 'agent.approval.approved' : 'agent.approval.rejected', entityType: 'AgentRun', entityId: runId, afterJson: { approvalId: approval.id, note: note ?? null }, requestReference: requestId } }); return { runId, approvalId: approval.id, status }; }

async function executeAction(auth: AuthContext, workspaceId: string, action: any, requestId: string) {
  if (action.tool === 'META' && action.action === 'CAMPAIGN_MUTATION') { if (!action.targetId) throw new AppError('VALIDATION_ERROR', 'Meta campaign targetId is required.', 400); return mutateMetaCampaign(auth, workspaceId, action.targetId, action.input ?? {}, requestId); }
  if (action.tool === 'META' && action.action === 'CAMPAIGN_DRAFT') return createMetaDraft(auth, workspaceId, action.input ?? {}, requestId);
  if (action.tool === 'ANALYTICS' || action.tool === 'CREATIVE') return { accepted: true, mode: 'INTERNAL_WORKFLOW', action: action.action, input: action.input ?? {} };
  throw new AppError('VALIDATION_ERROR', `No executor is registered for ${action.tool}:${action.action}.`, 400);
}

export async function executeAgentRun(auth: AuthContext, workspaceId: string, runId: string, requestId: string) { const membership = await access(auth, workspaceId); if (!['OWNER', 'ADMIN', 'MEMBER'].includes(membership.role)) throw new AppError('FORBIDDEN', 'You do not have permission to execute agent actions.', 403); const runs = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, status, permission_level FROM agent_runs WHERE id = ${runId} AND workspace_id = ${workspaceId} LIMIT 1`); const run = runs[0]; if (!run) throw new AppError('NOT_FOUND', 'Agent run not found.', 404); const configured = permission(run.permission_level); if (rank[configured] < rank.EXECUTE) throw new AppError('FORBIDDEN', 'Execution requires EXECUTE or AUTOMATE permission.', 403); const approval = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, status, expires_at FROM agent_approvals WHERE run_id = ${runId} AND workspace_id = ${workspaceId} ORDER BY created_at DESC LIMIT 1`); if (!approval[0] || approval[0].status !== 'APPROVED') throw new AppError('FORBIDDEN', 'An approved authorization is required before execution.', 403); if (approval[0].expires_at && new Date(approval[0].expires_at).getTime() <= Date.now()) throw new AppError('FORBIDDEN', 'Approval has expired.', 403); const actions = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, tool, action, permission_level, input_json FROM agent_actions WHERE run_id = ${runId} AND workspace_id = ${workspaceId} AND status = 'APPROVED' ORDER BY created_at ASC`); const results = []; for (const action of actions) { const level = permission(action.permission_level); assertActionPermission(level, configured); await prisma.$executeRaw(Prisma.sql`UPDATE agent_actions SET status = 'EXECUTING' WHERE id = ${action.id}`); try { const result = await executeAction(auth, workspaceId, action, requestId); await prisma.$executeRaw(Prisma.sql`UPDATE agent_actions SET status = 'SUCCEEDED', result_json = ${json(result)}, executed_at = NOW() WHERE id = ${action.id}`); results.push({ id: action.id, status: 'SUCCEEDED', result }); } catch (error) { const message = error instanceof Error ? error.message : 'Agent action failed.'; await prisma.$executeRaw(Prisma.sql`UPDATE agent_actions SET status = 'FAILED', error_message = ${message} WHERE id = ${action.id}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'agent.action.failed', entityType: 'AgentAction', entityId: action.id, afterJson: { tool: action.tool, action: action.action, error: message }, requestReference: requestId } }); throw error; } }
  await prisma.$executeRaw(Prisma.sql`UPDATE agent_runs SET status = 'SUCCEEDED', updated_at = NOW() WHERE id = ${runId}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'agent.run.executed', entityType: 'AgentRun', entityId: runId, afterJson: { actionCount: actions.length }, requestReference: requestId } }); return { runId, status: 'SUCCEEDED', results }; }

export async function listAutomationRules(auth: AuthContext, workspaceId: string) { await access(auth, workspaceId); return prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, name, enabled, permission_level AS "permissionLevel", trigger_json AS "trigger", action_json AS "action", cooldown_seconds AS "cooldownSeconds", last_run_at AS "lastRunAt", created_at AS "createdAt", updated_at AS "updatedAt" FROM automation_rules WHERE workspace_id = ${workspaceId} ORDER BY created_at DESC`); }
export async function createAutomationRule(auth: AuthContext, workspaceId: string, input: Record<string, unknown>, requestId: string) { const membership = await access(auth, workspaceId); if (!['OWNER', 'ADMIN'].includes(membership.role)) throw new AppError('FORBIDDEN', 'Only workspace owners or admins can manage automation rules.', 403); const name = text(input.name, 'name'); const level = permission(input.permissionLevel, 'RECOMMEND'); const cooldown = Number(input.cooldownSeconds ?? 3600); if (!Number.isInteger(cooldown) || cooldown < 60) throw new AppError('VALIDATION_ERROR', 'cooldownSeconds must be an integer of at least 60.', 400); const id = randomUUID(); await prisma.$executeRaw(Prisma.sql`INSERT INTO automation_rules (id, workspace_id, name, enabled, permission_level, trigger_json, action_json, cooldown_seconds, created_at, updated_at) VALUES (${id}, ${workspaceId}, ${name}, false, ${level}, ${json(input.trigger ?? {})}, ${json(input.action ?? {})}, ${cooldown}, NOW(), NOW())`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'agent.automation.created', entityType: 'AutomationRule', entityId: id, afterJson: { permissionLevel: level, enabled: false }, requestReference: requestId } }); return { id, name, enabled: false, permissionLevel: level }; }
export async function setAutomationRule(auth: AuthContext, workspaceId: string, ruleId: string, enabled: boolean, requestId: string) { const membership = await access(auth, workspaceId); if (!['OWNER', 'ADMIN'].includes(membership.role)) throw new AppError('FORBIDDEN', 'Only workspace owners or admins can manage automation rules.', 403); const rows = await prisma.$queryRaw<any[]>(Prisma.sql`SELECT id, permission_level FROM automation_rules WHERE id = ${ruleId} AND workspace_id = ${workspaceId} LIMIT 1`); if (!rows[0]) throw new AppError('NOT_FOUND', 'Automation rule not found.', 404); const level = permission(rows[0].permission_level); if (enabled && level !== 'AUTOMATE') throw new AppError('FORBIDDEN', 'Only AUTOMATE permission rules may be enabled.', 403); await prisma.$executeRaw(Prisma.sql`UPDATE automation_rules SET enabled = ${enabled}, updated_at = NOW() WHERE id = ${ruleId} AND workspace_id = ${workspaceId}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: enabled ? 'agent.automation.enabled' : 'agent.automation.disabled', entityType: 'AutomationRule', entityId: ruleId, afterJson: { enabled }, requestReference: requestId } }); return { id: ruleId, enabled }; }
