import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from 'node:crypto';
import type { IncomingMessage } from 'node:http';
import { Prisma } from '@prisma/client';
import { prisma } from '../infrastructure/database/client.js';
import { AppError } from '../shared/errors.js';
import type { AuthContext } from './auth.js';
import { requireWorkspaceAccess } from './workspaces.js';

const META_API = 'https://graph.facebook.com';
const STATE_TTL_MS = 10 * 60 * 1000;
const TOKEN_ALGORITHM = 'aes-256-gcm';

type MetaConfig = { appId: string; appSecret: string; redirectUri: string; graphVersion: string; scopes: string[]; encryptionKey: Buffer };
type MetaConnection = { id: string; workspaceId: string; userId: string; metaUserId: string; accessToken: string; tokenExpiresAt: Date | null };
type MetaObject = Record<string, unknown>;

function env(name: string): string { const value = process.env[name]?.trim(); if (!value) throw new AppError('CONFIGURATION_ERROR', `Missing Meta configuration: ${name}.`, 503); return value; }
function metaConfig(): MetaConfig { const key = Buffer.from(env('META_TOKEN_ENCRYPTION_KEY'), 'base64'); if (key.length !== 32) throw new AppError('CONFIGURATION_ERROR', 'META_TOKEN_ENCRYPTION_KEY must decode to 32 bytes.', 503); return { appId: env('META_APP_ID'), appSecret: env('META_APP_SECRET'), redirectUri: env('META_REDIRECT_URI'), graphVersion: env('META_GRAPH_API_VERSION'), scopes: (process.env.META_APP_SCOPES ?? 'ads_read,ads_management,business_management').split(',').map((value) => value.trim()).filter(Boolean), encryptionKey: key }; }
function hash(value: string): string { return createHash('sha256').update(value).digest('hex'); }
function encrypt(value: string, key: Buffer): { ciphertext: string; iv: string; tag: string } { const iv = randomBytes(12); const cipher = createCipheriv(TOKEN_ALGORITHM, key, iv); const ciphertext = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return { ciphertext: ciphertext.toString('base64'), iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64') }; }
function decrypt(ciphertext: string, iv: string, tag: string, key: Buffer): string { const decipher = createDecipheriv(TOKEN_ALGORITHM, key, Buffer.from(iv, 'base64')); decipher.setAuthTag(Buffer.from(tag, 'base64')); return Buffer.concat([decipher.update(Buffer.from(ciphertext, 'base64')), decipher.final()]).toString('utf8'); }
function requireAdmin(auth: AuthContext, workspaceId: string) { return requireWorkspaceAccess(auth, workspaceId).then((access) => { if (!['OWNER', 'ADMIN'].includes(access.role)) throw new AppError('FORBIDDEN', 'Meta account management requires workspace admin permission.', 403); return access; }); }
function safeJson(value: unknown): Prisma.InputJsonValue { return (value && typeof value === 'object' ? value : {}) as Prisma.InputJsonValue; }
function accountId(value: string): string { const normalized = value.trim().replace(/^act_/, ''); if (!/^\d+$/.test(normalized)) throw new AppError('VALIDATION_ERROR', 'Meta ad account ID is invalid.', 400); return normalized; }

async function metaFetch(path: string, token: string, init?: RequestInit): Promise<MetaObject> { const config = metaConfig(); const url = new URL(`${META_API}/${config.graphVersion}/${path.replace(/^\//, '')}`); if (!init?.body) url.searchParams.set('access_token', token); const response = await fetch(url, { ...init, headers: { accept: 'application/json', ...(init?.headers ?? {}) } }); const body = await response.json().catch(() => ({})) as MetaObject; if (!response.ok || body.error) { const error = body.error as MetaObject | undefined; throw new AppError('META_API_ERROR', typeof error?.message === 'string' ? error.message : `Meta API request failed with status ${response.status}.`, response.status >= 400 && response.status < 500 ? 400 : 502); } return body; }
async function metaPost(path: string, token: string, params: Record<string, string>): Promise<MetaObject> { const config = metaConfig(); const body = new URLSearchParams({ ...params, access_token: token }); const response = await fetch(`${META_API}/${config.graphVersion}/${path.replace(/^\//, '')}`, { method: 'POST', headers: { accept: 'application/json', 'content-type': 'application/x-www-form-urlencoded' }, body }); const result = await response.json().catch(() => ({})) as MetaObject; if (!response.ok || result.error) { const error = result.error as MetaObject | undefined; throw new AppError('META_API_ERROR', typeof error?.message === 'string' ? error.message : `Meta API mutation failed with status ${response.status}.`, response.status >= 400 && response.status < 500 ? 400 : 502); } return result; }

async function connectionForWorkspace(workspaceId: string): Promise<MetaConnection> { const config = metaConfig(); const rows = await prisma.$queryRaw<Array<{ id: string; workspace_id: string; user_id: string; meta_user_id: string; access_token_ciphertext: string; access_token_iv: string; access_token_tag: string; token_expires_at: Date | null }>>(Prisma.sql`SELECT id, workspace_id, user_id, meta_user_id, access_token_ciphertext, access_token_iv, access_token_tag, token_expires_at FROM meta_connections WHERE workspace_id = ${workspaceId} LIMIT 1`); const row = rows[0]; if (!row) throw new AppError('NOT_FOUND', 'No Meta account is connected to this workspace.', 404); if (row.token_expires_at && row.token_expires_at.getTime() <= Date.now()) throw new AppError('META_AUTH_EXPIRED', 'The Meta connection has expired and must be reconnected.', 401); return { id: row.id, workspaceId: row.workspace_id, userId: row.user_id, metaUserId: row.meta_user_id, accessToken: decrypt(row.access_token_ciphertext, row.access_token_iv, row.access_token_tag, config.encryptionKey), tokenExpiresAt: row.token_expires_at }; }

export async function beginMetaOAuth(auth: AuthContext, workspaceId: string) { await requireAdmin(auth, workspaceId); const config = metaConfig(); const rawState = randomUUID() + randomBytes(24).toString('hex'); const stateHash = hash(rawState); await prisma.$executeRaw(Prisma.sql`INSERT INTO meta_oauth_states (id, workspace_id, user_id, state_hash, expires_at, created_at) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, ${stateHash}, ${new Date(Date.now() + STATE_TTL_MS)}, NOW())`); const url = new URL(`https://www.facebook.com/${config.graphVersion}/dialog/oauth`); url.searchParams.set('client_id', config.appId); url.searchParams.set('redirect_uri', config.redirectUri); url.searchParams.set('state', rawState); url.searchParams.set('response_type', 'code'); url.searchParams.set('scope', config.scopes.join(',')); return { authorizationUrl: url.toString(), expiresInSeconds: STATE_TTL_MS / 1000 }; }

export async function completeMetaOAuth(request: IncomingMessage, requestId: string) { const url = new URL(request.url ?? '/', `http://${request.headers.host ?? 'localhost'}`); const code = url.searchParams.get('code'); const state = url.searchParams.get('state'); const error = url.searchParams.get('error'); if (error) throw new AppError('META_OAUTH_DENIED', url.searchParams.get('error_description') ?? 'Meta authorization was denied.', 400); if (!code || !state) throw new AppError('VALIDATION_ERROR', 'Meta OAuth callback is missing code or state.', 400); const rows = await prisma.$queryRaw<Array<{ id: string; workspace_id: string; user_id: string; expires_at: Date; used_at: Date | null }>>(Prisma.sql`SELECT id, workspace_id, user_id, expires_at, used_at FROM meta_oauth_states WHERE state_hash = ${hash(state)} LIMIT 1`); const oauth = rows[0]; if (!oauth || oauth.used_at || oauth.expires_at.getTime() <= Date.now()) throw new AppError('META_OAUTH_STATE_INVALID', 'The Meta OAuth state is invalid or expired.', 400); const config = metaConfig(); const tokenUrl = new URL(`${META_API}/${config.graphVersion}/oauth/access_token`); tokenUrl.searchParams.set('client_id', config.appId); tokenUrl.searchParams.set('client_secret', config.appSecret); tokenUrl.searchParams.set('redirect_uri', config.redirectUri); tokenUrl.searchParams.set('code', code); const tokenResponse = await fetch(tokenUrl); const tokenBody = await tokenResponse.json().catch(() => ({})) as MetaObject; if (!tokenResponse.ok || typeof tokenBody.access_token !== 'string') throw new AppError('META_OAUTH_FAILED', 'Meta token exchange failed.', 502); const shortLivedToken = tokenBody.access_token; const exchanged = await metaFetch('oauth/access_token', '', { method: 'GET' }); void exchanged;
  const me = await metaFetch('me?fields=id,name', shortLivedToken); const encrypted = encrypt(shortLivedToken, config.encryptionKey); const expiresIn = typeof tokenBody.expires_in === 'number' ? tokenBody.expires_in : null; const expiresAt = expiresIn ? new Date(Date.now() + expiresIn * 1000) : null; await prisma.$transaction(async (tx) => { await tx.$executeRaw(Prisma.sql`INSERT INTO meta_connections (id, workspace_id, user_id, meta_user_id, access_token_ciphertext, access_token_iv, access_token_tag, token_expires_at, created_at, updated_at) VALUES (${randomUUID()}, ${oauth.workspace_id}, ${oauth.user_id}, ${String(me.id)}, ${encrypted.ciphertext}, ${encrypted.iv}, ${encrypted.tag}, ${expiresAt}, NOW(), NOW()) ON CONFLICT (workspace_id) DO UPDATE SET user_id = EXCLUDED.user_id, meta_user_id = EXCLUDED.meta_user_id, access_token_ciphertext = EXCLUDED.access_token_ciphertext, access_token_iv = EXCLUDED.access_token_iv, access_token_tag = EXCLUDED.access_token_tag, token_expires_at = EXCLUDED.token_expires_at, updated_at = NOW()`); await tx.$executeRaw(Prisma.sql`UPDATE meta_oauth_states SET used_at = NOW() WHERE id = ${oauth.id}`); await tx.auditLog.create({ data: { workspaceId: oauth.workspace_id, userId: oauth.user_id, action: 'meta.oauth.connected', entityType: 'MetaConnection', afterJson: { metaUserId: String(me.id), name: me.name ?? null }, requestReference: requestId } }); }); return { connected: true, workspaceId: oauth.workspace_id, metaUser: { id: String(me.id), name: typeof me.name === 'string' ? me.name : null } }; }

export async function getMetaConnection(auth: AuthContext, workspaceId: string) { await requireWorkspaceAccess(auth, workspaceId); const rows = await prisma.$queryRaw<Array<{ id: string; meta_user_id: string; token_expires_at: Date | null; created_at: Date; updated_at: Date }>>(Prisma.sql`SELECT id, meta_user_id, token_expires_at, created_at, updated_at FROM meta_connections WHERE workspace_id = ${workspaceId} LIMIT 1`); const row = rows[0]; return row ? { connected: true, id: row.id, metaUserId: row.meta_user_id, tokenExpiresAt: row.token_expires_at, createdAt: row.created_at, updatedAt: row.updated_at } : { connected: false }; }

export async function discoverMetaAccounts(auth: AuthContext, workspaceId: string, requestId: string) { await requireAdmin(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const result = await metaFetch('me/adaccounts?fields=id,name,account_id,account_status,currency,timezone_name&limit=100', connection.accessToken); const accounts = Array.isArray(result.data) ? result.data as MetaObject[] : []; await persistMappings(workspaceId, connection.id, 'AD_ACCOUNT', accounts, 'account_id'); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.accounts.discover', entityType: 'MetaConnection', entityId: connection.id, afterJson: { count: accounts.length }, requestReference: requestId } }); return { data: accounts.map((account) => ({ id: String(account.id), name: account.name ?? null, accountId: account.account_id ?? null, status: account.account_status ?? null, currency: account.currency ?? null, timezone: account.timezone_name ?? null })) }; }

async function persistMappings(workspaceId: string, connectionId: string, resourceType: string, resources: MetaObject[], idField = 'id') { for (const resource of resources) { const externalId = String(resource.id ?? resource[idField] ?? ''); if (!externalId) continue; await prisma.$executeRaw(Prisma.sql`INSERT INTO meta_resource_mappings (id, workspace_id, connection_id, resource_type, external_id, local_entity_type, local_entity_id, name, metadata, created_at, updated_at) VALUES (${randomUUID()}, ${workspaceId}, ${connectionId}, ${resourceType}, ${externalId}, NULL, NULL, ${typeof resource.name === 'string' ? resource.name : null}, ${safeJson(resource)}, NOW(), NOW()) ON CONFLICT (connection_id, resource_type, external_id) DO UPDATE SET name = EXCLUDED.name, metadata = EXCLUDED.metadata, updated_at = NOW()`); } }
async function mappedAccount(workspaceId: string, connectionId: string, externalId: string) { const rows = await prisma.$queryRaw<Array<{ external_id: string }>>(Prisma.sql`SELECT external_id FROM meta_resource_mappings WHERE workspace_id = ${workspaceId} AND connection_id = ${connectionId} AND resource_type = 'AD_ACCOUNT' AND (external_id = ${externalId} OR external_id = ${`act_${externalId}`}) LIMIT 1`); return rows[0]?.external_id?.replace(/^act_/, '') ?? externalId.replace(/^act_/, ''); }

export async function syncMetaCampaigns(auth: AuthContext, workspaceId: string, metaAccountId: string, requestId: string) { await requireWorkspaceAccess(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const account = await mappedAccount(workspaceId, connection.id, accountId(metaAccountId)); const campaigns = await metaPaged(`act_${account}/campaigns?fields=id,name,status,objective,daily_budget,lifetime_budget,start_time,stop_time&limit=100`, connection.accessToken); await persistMappings(workspaceId, connection.id, 'CAMPAIGN', campaigns, 'id'); await prisma.$executeRaw(Prisma.sql`UPDATE meta_resource_mappings SET metadata = metadata || ${safeJson({ syncedAt: new Date().toISOString() })}::jsonb WHERE workspace_id = ${workspaceId} AND connection_id = ${connection.id} AND resource_type = 'AD_ACCOUNT' AND external_id = ${account}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.campaigns.sync', entityType: 'MetaAccount', entityId: account, afterJson: { count: campaigns.length }, requestReference: requestId } }); return { data: campaigns }; }
export async function syncMetaAdSets(auth: AuthContext, workspaceId: string, campaignExternalId: string, requestId: string) { await requireWorkspaceAccess(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const adSets = await metaPaged(`${campaignExternalId}/adsets?fields=id,name,status,daily_budget,lifetime_budget,targeting,optimization_goal,billing_event&limit=100`, connection.accessToken); await persistMappings(workspaceId, connection.id, 'ADSET', adSets); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.adsets.sync', entityType: 'MetaCampaign', entityId: campaignExternalId, afterJson: { count: adSets.length }, requestReference: requestId } }); return { data: adSets }; }
export async function syncMetaAds(auth: AuthContext, workspaceId: string, adSetExternalId: string, requestId: string) { await requireWorkspaceAccess(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const ads = await metaPaged(`${adSetExternalId}/ads?fields=id,name,status,creative,tracking_specs&limit=100`, connection.accessToken); await persistMappings(workspaceId, connection.id, 'AD', ads); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.ads.sync', entityType: 'MetaAdSet', entityId: adSetExternalId, afterJson: { count: ads.length }, requestReference: requestId } }); return { data: ads }; }

async function metaPaged(path: string, token: string): Promise<MetaObject[]> { const items: MetaObject[] = []; let next: string | null = `${META_API}/${metaConfig().graphVersion}/${path}`; while (next && items.length < 5000) { const response = await fetch(next.includes('access_token=') ? next : `${next}${next.includes('?') ? '&' : '?'}access_token=${encodeURIComponent(token)}`, { headers: { accept: 'application/json' } }); const body = await response.json().catch(() => ({})) as MetaObject; if (!response.ok || body.error) throw new AppError('META_API_ERROR', 'Meta pagination request failed.', response.status >= 400 && response.status < 500 ? 400 : 502); if (Array.isArray(body.data)) items.push(...body.data as MetaObject[]); const paging = body.paging as MetaObject | undefined; next = typeof paging?.next === 'string' ? paging.next : null; } return items; }

export async function syncMetaInsights(auth: AuthContext, workspaceId: string, campaignExternalId: string, start: string, end: string, requestId: string) { await requireWorkspaceAccess(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const fields = 'campaign_id,campaign_name,date_start,date_stop,impressions,clicks,reach,spend,actions,action_values,cpm,ctr,cpc'; const result = await metaFetch(`${campaignExternalId}/insights?fields=${fields}&time_range=${encodeURIComponent(JSON.stringify({ since: start, until: end }))}&time_increment=1&limit=500`, connection.accessToken); const rows = Array.isArray(result.data) ? result.data as MetaObject[] : []; const mapping = await prisma.$queryRaw<Array<{ local_entity_id: string | null }>>(Prisma.sql`SELECT local_entity_id FROM meta_resource_mappings WHERE workspace_id = ${workspaceId} AND connection_id = ${connection.id} AND resource_type = 'CAMPAIGN' AND external_id = ${campaignExternalId} LIMIT 1`); const localCampaignId = mapping[0]?.local_entity_id; let persisted = 0; if (localCampaignId) { for (const row of rows) { const periodStart = new Date(`${String(row.date_start)}T00:00:00.000Z`); const periodEnd = new Date(`${String(row.date_stop)}T23:59:59.999Z`); const spend = typeof row.spend === 'string' ? Number(row.spend) : Number(row.spend ?? 0); const impressions = Number(row.impressions ?? 0); const clicks = Number(row.clicks ?? 0); const reach = Number(row.reach ?? 0); const conversions = extractActionValue(row.actions, ['purchase', 'lead', 'complete_registration']); const revenue = extractActionValue(row.action_values, ['purchase']); const existing = await prisma.performanceSnapshot.findFirst({ where: { workspaceId, campaignId: localCampaignId, provider: 'META', entityType: 'CAMPAIGN', entityId: campaignExternalId, periodStart, periodEnd } }); const data = { workspaceId, campaignId: localCampaignId, entityType: 'CAMPAIGN', entityId: campaignExternalId, provider: 'META', periodStart, periodEnd, impressions, clicks, reach, spend, conversions, revenue, currency: 'DZD', sourceTimestamp: new Date() }; if (existing) await prisma.performanceSnapshot.update({ where: { id: existing.id }, data }); else await prisma.performanceSnapshot.create({ data }); persisted += 1; } } await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.insights.sync', entityType: 'MetaCampaign', entityId: campaignExternalId, afterJson: { rows: rows.length, persisted, start, end }, requestReference: requestId } }); return { data: rows, persisted }; }
function extractActionValue(value: unknown, types: string[]): number { if (!Array.isArray(value)) return 0; const found = (value as MetaObject[]).find((item) => types.includes(String(item.action_type))); return found ? Number(found.value ?? 0) || 0 : 0; }

export async function createMetaDraft(auth: AuthContext, workspaceId: string, input: Record<string, unknown>, requestId: string) { await requireAdmin(auth, workspaceId); const connection = await connectionForWorkspace(workspaceId); const localCampaignId = typeof input.campaignId === 'string' ? input.campaignId : ''; const metaAccountId = accountId(typeof input.metaAccountId === 'string' ? input.metaAccountId : ''); const campaign = await prisma.campaign.findFirst({ where: { id: localCampaignId, workspaceId } }); if (!campaign) throw new AppError('NOT_FOUND', 'Local campaign not found.', 404); const objectiveMap: Record<string, string> = { SALES: 'OUTCOME_SALES', LEADS: 'OUTCOME_LEADS', MESSAGES: 'OUTCOME_ENGAGEMENT', TRAFFIC: 'OUTCOME_TRAFFIC', WEBSITE_CONVERSIONS: 'OUTCOME_SALES' }; const result = await metaPost(`act_${metaAccountId}/campaigns`, connection.accessToken, { name: campaign.name, objective: objectiveMap[campaign.objective] ?? 'OUTCOME_SALES', status: 'PAUSED', special_ad_categories: '[]' }); const externalId = String(result.id ?? ''); if (!externalId) throw new AppError('META_API_ERROR', 'Meta did not return a campaign ID.', 502); await prisma.$executeRaw(Prisma.sql`INSERT INTO meta_resource_mappings (id, workspace_id, connection_id, resource_type, external_id, local_entity_type, local_entity_id, name, metadata, created_at, updated_at) VALUES (${randomUUID()}, ${workspaceId}, ${connection.id}, 'CAMPAIGN', ${externalId}, 'Campaign', ${localCampaignId}, ${campaign.name}, ${safeJson({ draft: true })}, NOW(), NOW()) ON CONFLICT (connection_id, resource_type, external_id) DO UPDATE SET local_entity_type = EXCLUDED.local_entity_type, local_entity_id = EXCLUDED.local_entity_id, name = EXCLUDED.name, metadata = EXCLUDED.metadata, updated_at = NOW()`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: 'meta.campaign.draft.create', entityType: 'Campaign', entityId: localCampaignId, afterJson: { metaCampaignId: externalId, accountId: metaAccountId, status: 'PAUSED' }, requestReference: requestId } }); return { localCampaignId, metaCampaignId: externalId, status: 'PAUSED' }; }

export async function mutateMetaCampaign(auth: AuthContext, workspaceId: string, metaCampaignId: string, input: Record<string, unknown>, requestId: string) { await requireAdmin(auth, workspaceId); if (input.approved !== true) throw new AppError('APPROVAL_REQUIRED', 'External Meta mutations require explicit approval.', 403); const action = input.action; if (!['PUBLISH', 'PAUSE', 'RESUME'].includes(String(action))) throw new AppError('VALIDATION_ERROR', 'Action must be PUBLISH, PAUSE or RESUME.', 400); const connection = await connectionForWorkspace(workspaceId); const mapping = await prisma.$queryRaw<Array<{ id: string; local_entity_id: string | null }>>(Prisma.sql`SELECT id, local_entity_id FROM meta_resource_mappings WHERE workspace_id = ${workspaceId} AND connection_id = ${connection.id} AND resource_type = 'CAMPAIGN' AND external_id = ${metaCampaignId} LIMIT 1`); if (!mapping[0]) throw new AppError('NOT_FOUND', 'Meta campaign is not mapped to this workspace.', 404); const status = action === 'PAUSE' ? 'PAUSED' : 'ACTIVE'; await metaPost(metaCampaignId, connection.accessToken, { status }); await prisma.$executeRaw(Prisma.sql`UPDATE meta_resource_mappings SET metadata = metadata || ${safeJson({ lastMutation: { action, status, at: new Date().toISOString() } })}::jsonb, updated_at = NOW() WHERE id = ${mapping[0].id}`); await prisma.auditLog.create({ data: { workspaceId, userId: auth.userId, action: `meta.campaign.${String(action).toLowerCase()}`, entityType: 'MetaCampaign', entityId: metaCampaignId, afterJson: { status, approved: true, localCampaignId: mapping[0].local_entity_id ?? null }, requestReference: requestId } }); return { metaCampaignId, action, status, approved: true }; }

export const metaTestables = { hash, encrypt, decrypt, accountId, buildOAuthUrl: (config: Pick<MetaConfig, 'appId' | 'graphVersion' | 'redirectUri' | 'scopes'>, state: string) => { const url = new URL(`https://www.facebook.com/${config.graphVersion}/dialog/oauth`); url.searchParams.set('client_id', config.appId); url.searchParams.set('redirect_uri', config.redirectUri); url.searchParams.set('state', state); url.searchParams.set('response_type', 'code'); url.searchParams.set('scope', config.scopes.join(',')); return url.toString(); } };
