import { randomUUID } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../infrastructure/database/client.js';
import { AppError } from '../shared/errors.js';
import type { AuthContext } from './auth.js';
import { requireWorkspaceAccess } from './workspaces.js';

export type OrderStatus = 'DRAFT' | 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'RETURNED';
export type ShipmentStatus = 'PENDING' | 'LABEL_CREATED' | 'PICKED_UP' | 'IN_TRANSIT' | 'DELIVERED' | 'RETURNED' | 'CANCELLED' | 'FAILED';

const ORDER_STATUSES: OrderStatus[] = ['DRAFT','PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURNED'];
const SHIPMENT_STATUSES: ShipmentStatus[] = ['PENDING','LABEL_CREATED','PICKED_UP','IN_TRANSIT','DELIVERED','RETURNED','CANCELLED','FAILED'];

function text(value: unknown, field: string, required = true): string | null {
  if (value === undefined || value === null) { if (required) throw new AppError('VALIDATION_ERROR', `${field} is required.`, 400); return null; }
  const result = String(value).trim(); if (!result && required) throw new AppError('VALIDATION_ERROR', `${field} is required.`, 400); return result || null;
}
function money(value: unknown, field: string, fallback = 0): number {
  if (value === undefined || value === null || value === '') return fallback;
  const result = Number(value); if (!Number.isFinite(result) || result < 0) throw new AppError('VALIDATION_ERROR', `${field} must be a non-negative number.`, 400); return result;
}
function positiveInt(value: unknown, field: string): number { const result = Number(value); if (!Number.isInteger(result) || result <= 0) throw new AppError('VALIDATION_ERROR', `${field} must be a positive integer.`, 400); return result; }
function normalizeStatus(value: unknown, field: string, allowed: string[]): string { const result = String(value ?? '').trim().toUpperCase(); if (!allowed.includes(result)) throw new AppError('VALIDATION_ERROR', `Invalid ${field}.`, 400); return result; }
function serialize(row: Record<string, unknown>): Record<string, unknown> { return Object.fromEntries(Object.entries(row).map(([key, value]) => value instanceof Prisma.Decimal ? [key, value.toString()] : [key, value])); }
function calculateProfit(revenue: number, productCost: number, shippingCost: number, packagingCost: number, adSpend: number, otherCost: number) { return revenue - productCost - shippingCost - packagingCost - adSpend - otherCost; }
export function calculateOrderTotals(items: Array<{ quantity: number; unitPrice: number }>, shippingCost: number, packagingCost: number, discount: number) { const subtotal = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); return { subtotal, total: Math.max(0, subtotal + shippingCost + packagingCost - discount) }; }

async function access(auth: AuthContext, workspaceId: string) { return requireWorkspaceAccess(auth, workspaceId); }
async function writable(auth: AuthContext, workspaceId: string) { const member = await access(auth, workspaceId); if (!['OWNER','ADMIN','MEMBER'].includes(member.role)) throw new AppError('FORBIDDEN', 'You do not have permission to modify orders.', 403); }
async function ensureCustomer(workspaceId: string, customerId: string) { const rows = await prisma.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT id FROM customers WHERE id = ${customerId} AND workspace_id = ${workspaceId}`); if (!rows[0]) throw new AppError('VALIDATION_ERROR', 'Customer does not belong to this workspace.', 400); }
async function ensureCampaign(workspaceId: string, campaignId: string | null) { if (!campaignId) return; const rows = await prisma.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT id FROM campaigns WHERE id = ${campaignId} AND workspace_id = ${workspaceId}`); if (!rows[0]) throw new AppError('VALIDATION_ERROR', 'Campaign does not belong to this workspace.', 400); }

export async function listCustomers(auth: AuthContext, workspaceId: string, search?: string) { await access(auth, workspaceId); const term = search?.trim(); const rows = term ? await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM customers WHERE workspace_id = ${workspaceId} AND (name ILIKE ${`%${term}%`} OR phone ILIKE ${`%${term}%`}) ORDER BY created_at DESC LIMIT 100`) : await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM customers WHERE workspace_id = ${workspaceId} ORDER BY created_at DESC LIMIT 100`); return rows.map(serialize); }

export async function createCustomer(auth: AuthContext, workspaceId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const name = text(input.name, 'name')!; const phone = text(input.phone, 'phone')!; const existing = await prisma.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT id FROM customers WHERE workspace_id = ${workspaceId} AND phone = ${phone} LIMIT 1`); if (existing[0]) throw new AppError('CONFLICT', 'A customer with this phone already exists in the workspace.', 409); const id = randomUUID(); await prisma.$executeRaw(Prisma.sql`INSERT INTO customers (id, workspace_id, name, phone, email, address_line, city, state, country_code, notes) VALUES (${id}, ${workspaceId}, ${name}, ${phone}, ${text(input.email, 'email', false)}, ${text(input.addressLine, 'addressLine', false)}, ${text(input.city, 'city', false)}, ${text(input.state, 'state', false)}, ${String(input.countryCode ?? 'DZ').trim().toUpperCase()}, ${text(input.notes, 'notes', false)})`); await prisma.$executeRaw(Prisma.sql`INSERT INTO audit_logs (id, workspace_id, user_id, action, entity_type, entity_id, after_json, request_reference) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, 'customer.create', 'Customer', ${id}, ${JSON.stringify({ name, phone })}::jsonb, ${requestId})`); const rows = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM customers WHERE id = ${id}`); return serialize(rows[0]); }

export async function listOrders(auth: AuthContext, workspaceId: string, status?: string) { await access(auth, workspaceId); if (status) normalizeStatus(status, 'status', ORDER_STATUSES); const rows = status ? await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT o.*, c.name AS customer_name, c.phone AS customer_phone FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.workspace_id = ${workspaceId} AND o.status = ${status!.toUpperCase()}::"OrderStatus" ORDER BY o.created_at DESC LIMIT 200`) : await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT o.*, c.name AS customer_name, c.phone AS customer_phone FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.workspace_id = ${workspaceId} ORDER BY o.created_at DESC LIMIT 200`); return rows.map(serialize); }

export async function getOrder(auth: AuthContext, workspaceId: string, orderId: string) { await access(auth, workspaceId); const orders = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT o.*, c.name AS customer_name, c.phone AS customer_phone, c.address_line, c.city, c.state, c.country_code FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.id = ${orderId} AND o.workspace_id = ${workspaceId}`); if (!orders[0]) throw new AppError('NOT_FOUND', 'Order not found.', 404); const items = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM order_items WHERE order_id = ${orderId} ORDER BY created_at ASC`); const shipments = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM shipments WHERE order_id = ${orderId}`); const profit = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM profit_records WHERE order_id = ${orderId}`); const attribution = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM attribution_records WHERE order_id = ${orderId}`); return { ...serialize(orders[0]), items: items.map(serialize), shipment: shipments[0] ? serialize(shipments[0]) : null, profit: profit[0] ? serialize(profit[0]) : null, attribution: attribution[0] ? serialize(attribution[0]) : null }; }

export async function createOrder(auth: AuthContext, workspaceId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const customerId = text(input.customerId, 'customerId')!; await ensureCustomer(workspaceId, customerId); const campaignId = text(input.campaignId, 'campaignId', false); await ensureCampaign(workspaceId, campaignId); const currency = String(input.currency ?? 'DZD').trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new AppError('VALIDATION_ERROR', 'Currency must be a 3-letter ISO-style code.', 400); const rawItems = input.items; if (!Array.isArray(rawItems) || rawItems.length === 0) throw new AppError('VALIDATION_ERROR', 'At least one order item is required.', 400); const items: Array<{ productId: string | null; variantId: string | null; name: string; sku: string | null; quantity: number; unitPrice: number; unitCost: number }> = []; for (const raw of rawItems) { if (!raw || typeof raw !== 'object') throw new AppError('VALIDATION_ERROR', 'Invalid order item.', 400); const item = raw as Record<string, unknown>; const productId = text(item.productId, 'productId', false); const variantId = text(item.variantId, 'variantId', false); let name = text(item.name, 'item.name', false); let sku = text(item.sku, 'item.sku', false); let unitPrice = money(item.unitPrice, 'item.unitPrice', 0); let unitCost = money(item.unitCost, 'item.unitCost', 0); if (productId) { const products = await prisma.$queryRaw<Array<{ name: string; sku: string | null; sale_price: string; base_cost: string }>>(Prisma.sql`SELECT name, sku, sale_price, base_cost FROM products WHERE id = ${productId} AND workspace_id = ${workspaceId}`); if (!products[0]) throw new AppError('VALIDATION_ERROR', 'Product does not belong to this workspace.', 400); name ??= products[0].name; sku ??= products[0].sku; if (unitPrice === 0) unitPrice = Number(products[0].sale_price); if (unitCost === 0) unitCost = Number(products[0].base_cost); } if (!name) throw new AppError('VALIDATION_ERROR', 'Each item requires a name or productId.', 400); const quantity = positiveInt(item.quantity, 'item.quantity'); items.push({ productId, variantId, name, sku, quantity, unitPrice, unitCost }); }
  const shippingCost = money(input.shippingCost, 'shippingCost'); const packagingCost = money(input.packagingCost, 'packagingCost'); const discount = money(input.discount, 'discount'); const totals = calculateOrderTotals(items, shippingCost, packagingCost, discount); const expectedRevenue = money(input.expectedRevenue, 'expectedRevenue', totals.total); const orderId = randomUUID(); const now = new Date(); const adSpend = money(input.adSpend, 'adSpend'); const productCost = items.reduce((sum, item) => sum + item.quantity * item.unitCost, 0); const expectedProfit = calculateProfit(expectedRevenue, productCost, shippingCost, packagingCost, adSpend, money(input.otherCost, 'otherCost')); await prisma.$transaction(async (tx) => { await tx.$executeRaw(Prisma.sql`INSERT INTO orders (id, workspace_id, customer_id, campaign_id, status, payment_method, payment_status, currency, subtotal, shipping_cost, packaging_cost, discount, total, expected_revenue, notes, source) VALUES (${orderId}, ${workspaceId}, ${customerId}, ${campaignId}, 'PENDING'::"OrderStatus", ${String(input.paymentMethod ?? 'COD').toUpperCase()}::"PaymentMethod", 'PENDING'::"PaymentStatus", ${currency}, ${totals.subtotal}, ${shippingCost}, ${packagingCost}, ${discount}, ${totals.total}, ${expectedRevenue}, ${text(input.notes, 'notes', false)}, ${text(input.source, 'source', false)})`); for (const item of items) { await tx.$executeRaw(Prisma.sql`INSERT INTO order_items (id, order_id, product_id, variant_id, name, sku, quantity, unit_price, unit_cost, line_total) VALUES (${randomUUID()}, ${orderId}, ${item.productId}, ${item.variantId}, ${item.name}, ${item.sku}, ${item.quantity}, ${item.unitPrice}, ${item.unitCost}, ${item.quantity * item.unitPrice})`); } await tx.$executeRaw(Prisma.sql`INSERT INTO profit_records (id, workspace_id, order_id, source, revenue, product_cost, shipping_cost, packaging_cost, ad_spend, other_cost, profit, currency) VALUES (${randomUUID()}, ${workspaceId}, ${orderId}, 'ESTIMATED'::"ProfitSource", ${expectedRevenue}, ${productCost}, ${shippingCost}, ${packagingCost}, ${adSpend}, ${money(input.otherCost, 'otherCost')}, ${expectedProfit}, ${currency})`); if (campaignId) await tx.$executeRaw(Prisma.sql`INSERT INTO attribution_records (id, workspace_id, order_id, campaign_id, source, attributed_revenue) VALUES (${randomUUID()}, ${workspaceId}, ${orderId}, ${campaignId}, ${text(input.attributionSource, 'attributionSource', false) ?? 'manual'}, ${expectedRevenue})`); await tx.$executeRaw(Prisma.sql`INSERT INTO audit_logs (id, workspace_id, user_id, action, entity_type, entity_id, after_json, request_reference) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, 'order.create', 'Order', ${orderId}, ${JSON.stringify({ total: totals.total, status: 'PENDING' })}::jsonb, ${requestId})`); }); return getOrder(auth, workspaceId, orderId); }

async function recomputeProfit(workspaceId: string, orderId: string, actual: boolean) { const orders = await prisma.$queryRaw<Array<{ total: string; expected_revenue: string | null; shipping_cost: string; packaging_cost: string; currency: string }>>(Prisma.sql`SELECT total, expected_revenue, shipping_cost, packaging_cost, currency FROM orders WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); if (!orders[0]) throw new AppError('NOT_FOUND', 'Order not found.', 404); const items = await prisma.$queryRaw<Array<{ quantity: number; unit_cost: string }>>(Prisma.sql`SELECT quantity, unit_cost FROM order_items WHERE order_id = ${orderId}`); const profit = await prisma.$queryRaw<Array<{ ad_spend: string; other_cost: string }>>(Prisma.sql`SELECT ad_spend, other_cost FROM profit_records WHERE order_id = ${orderId}`); const revenue = actual ? Number(orders[0].total) : Number(orders[0].expected_revenue ?? orders[0].total); const productCost = items.reduce((sum, item) => sum + item.quantity * Number(item.unit_cost), 0); const shipping = Number(orders[0].shipping_cost); const packaging = Number(orders[0].packaging_cost); const adSpend = Number(profit[0]?.ad_spend ?? 0); const otherCost = Number(profit[0]?.other_cost ?? 0); const result = calculateProfit(revenue, productCost, shipping, packaging, adSpend, otherCost); await prisma.$executeRaw(Prisma.sql`UPDATE profit_records SET source = ${actual ? 'ACTUAL' : 'ESTIMATED'}::"ProfitSource", revenue = ${revenue}, product_cost = ${productCost}, shipping_cost = ${shipping}, packaging_cost = ${packaging}, profit = ${result}, updated_at = CURRENT_TIMESTAMP WHERE order_id = ${orderId} AND workspace_id = ${workspaceId}`); await prisma.$executeRaw(Prisma.sql`UPDATE orders SET actual_revenue = ${actual ? revenue : null}, updated_at = CURRENT_TIMESTAMP WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); return { revenue, productCost, shippingCost: shipping, packagingCost: packaging, adSpend, otherCost, profit: result, currency: orders[0].currency, source: actual ? 'ACTUAL' : 'ESTIMATED' }; }

export async function updateOrderStatus(auth: AuthContext, workspaceId: string, orderId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const status = normalizeStatus(input.status, 'status', ORDER_STATUSES) as OrderStatus; const orders = await prisma.$queryRaw<Array<{ id: string; payment_method: string }>>(Prisma.sql`SELECT id, payment_method FROM orders WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); if (!orders[0]) throw new AppError('NOT_FOUND', 'Order not found.', 404); const paymentStatus = status === 'DELIVERED' && orders[0].payment_method === 'COD' ? 'PAID' : status === 'RETURNED' || status === 'CANCELLED' ? 'REFUNDED' : undefined; await prisma.$executeRaw(Prisma.sql`UPDATE orders SET status = ${status}::"OrderStatus", payment_status = COALESCE(${paymentStatus}::"PaymentStatus", payment_status), updated_at = CURRENT_TIMESTAMP WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); if (status === 'DELIVERED') await recomputeProfit(workspaceId, orderId, true); else if (status === 'RETURNED' || status === 'CANCELLED') await recomputeProfit(workspaceId, orderId, false); await prisma.$executeRaw(Prisma.sql`INSERT INTO audit_logs (id, workspace_id, user_id, action, entity_type, entity_id, after_json, request_reference) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, 'order.status.update', 'Order', ${orderId}, ${JSON.stringify({ status })}::jsonb, ${requestId})`); return getOrder(auth, workspaceId, orderId); }

export async function createOrGetShipment(auth: AuthContext, workspaceId: string, orderId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const order = await prisma.$queryRaw<Array<{ id: string; total: string }>>(Prisma.sql`SELECT id, total FROM orders WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); if (!order[0]) throw new AppError('NOT_FOUND', 'Order not found.', 404); const existing = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM shipments WHERE order_id = ${orderId}`); if (existing[0]) return serialize(existing[0]); const id = randomUUID(); const provider = String(input.provider ?? 'MANUAL').trim().toUpperCase(); const shippingCost = money(input.shippingCost, 'shippingCost'); const codAmount = money(input.codAmount, 'codAmount', Number(order[0].total)); await prisma.$executeRaw(Prisma.sql`INSERT INTO shipments (id, workspace_id, order_id, provider, provider_shipment_id, status, tracking_number, shipping_cost, cod_amount, estimated_delivery_at, metadata) VALUES (${id}, ${workspaceId}, ${provider}, ${text(input.providerShipmentId, 'providerShipmentId', false)}, 'PENDING'::"ShipmentStatus", ${text(input.trackingNumber, 'trackingNumber', false)}, ${shippingCost}, ${codAmount}, ${input.estimatedDeliveryAt ? new Date(String(input.estimatedDeliveryAt)) : null}, ${JSON.stringify(input.metadata ?? {})}::jsonb)`); await prisma.$executeRaw(Prisma.sql`INSERT INTO audit_logs (id, workspace_id, user_id, action, entity_type, entity_id, after_json, request_reference) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, 'shipment.create', 'Shipment', ${id}, ${JSON.stringify({ orderId, provider })}::jsonb, ${requestId})`); const rows = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM shipments WHERE id = ${id}`); return serialize(rows[0]); }

export async function updateShipment(auth: AuthContext, workspaceId: string, shipmentId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const shipments = await prisma.$queryRaw<Array<{ id: string; order_id: string }>>(Prisma.sql`SELECT id, order_id FROM shipments WHERE id = ${shipmentId} AND workspace_id = ${workspaceId}`); if (!shipments[0]) throw new AppError('NOT_FOUND', 'Shipment not found.', 404); const status = normalizeStatus(input.status, 'status', SHIPMENT_STATUSES) as ShipmentStatus; await prisma.$executeRaw(Prisma.sql`UPDATE shipments SET status = ${status}::"ShipmentStatus", tracking_number = COALESCE(${text(input.trackingNumber, 'trackingNumber', false)}, tracking_number), delivered_at = CASE WHEN ${status} = 'DELIVERED'::"ShipmentStatus" THEN CURRENT_TIMESTAMP ELSE delivered_at END, returned_at = CASE WHEN ${status} = 'RETURNED'::"ShipmentStatus" THEN CURRENT_TIMESTAMP ELSE returned_at END, updated_at = CURRENT_TIMESTAMP WHERE id = ${shipmentId} AND workspace_id = ${workspaceId}`); const orderStatus: OrderStatus | null = status === 'DELIVERED' ? 'DELIVERED' : status === 'RETURNED' ? 'RETURNED' : status === 'IN_TRANSIT' || status === 'PICKED_UP' ? 'SHIPPED' : null; if (orderStatus) await updateOrderStatus(auth, workspaceId, shipments[0].order_id, { status: orderStatus }, requestId); const rows = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM shipments WHERE id = ${shipmentId}`); return serialize(rows[0]); }

export async function getProfitDashboard(auth: AuthContext, workspaceId: string, start?: string, end?: string) { await access(auth, workspaceId); const startDate = start ? new Date(start) : new Date(Date.now() - 30 * 86400000); const endDate = end ? new Date(end) : new Date(); if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime()) || endDate <= startDate) throw new AppError('VALIDATION_ERROR', 'Invalid profit dashboard date window.', 400); const totals = await prisma.$queryRaw<Array<{ orders: bigint; delivered: bigint; returned: bigint; revenue: string; profit: string; ad_spend: string }>>(Prisma.sql`SELECT COUNT(*)::bigint AS orders, COUNT(*) FILTER (WHERE status = 'DELIVERED')::bigint AS delivered, COUNT(*) FILTER (WHERE status = 'RETURNED')::bigint AS returned, COALESCE(SUM(CASE WHEN status = 'DELIVERED' THEN actual_revenue ELSE expected_revenue END),0) AS revenue, COALESCE(SUM(p.profit),0) AS profit, COALESCE(SUM(p.ad_spend),0) AS ad_spend FROM orders o LEFT JOIN profit_records p ON p.order_id = o.id WHERE o.workspace_id = ${workspaceId} AND o.created_at >= ${startDate} AND o.created_at <= ${endDate}`); const byStatus = await prisma.$queryRaw<Array<{ status: OrderStatus; count: bigint; value: string }>>(Prisma.sql`SELECT status, COUNT(*)::bigint AS count, COALESCE(SUM(total),0) AS value FROM orders WHERE workspace_id = ${workspaceId} AND created_at >= ${startDate} AND created_at <= ${endDate} GROUP BY status ORDER BY status`); const row = totals[0]; const orders = Number(row?.orders ?? 0); const delivered = Number(row?.delivered ?? 0); const returned = Number(row?.returned ?? 0); return { window: { start: startDate.toISOString(), end: endDate.toISOString() }, orders, delivered, returned, deliveryRate: orders ? delivered / orders : 0, returnRate: orders ? returned / orders : 0, revenue: Number(row?.revenue ?? 0), profit: Number(row?.profit ?? 0), adSpend: Number(row?.ad_spend ?? 0), roas: Number(row?.ad_spend ?? 0) > 0 ? Number(row?.revenue ?? 0) / Number(row?.ad_spend ?? 0) : null, byStatus: byStatus.map((item) => ({ status: item.status, count: Number(item.count), value: Number(item.value) })) }; }

export async function recordAttribution(auth: AuthContext, workspaceId: string, orderId: string, input: Record<string, unknown>, requestId: string) { await writable(auth, workspaceId); const order = await prisma.$queryRaw<Array<{ id: string; total: string }>>(Prisma.sql`SELECT id, total FROM orders WHERE id = ${orderId} AND workspace_id = ${workspaceId}`); if (!order[0]) throw new AppError('NOT_FOUND', 'Order not found.', 404); const campaignId = text(input.campaignId, 'campaignId', false); await ensureCampaign(workspaceId, campaignId); const id = randomUUID(); await prisma.$executeRaw(Prisma.sql`INSERT INTO attribution_records (id, workspace_id, order_id, campaign_id, ad_set_id, ad_id, source, external_click_id, attributed_revenue) VALUES (${id}, ${workspaceId}, ${orderId}, ${campaignId}, ${text(input.adSetId, 'adSetId', false)}, ${text(input.adId, 'adId', false)}, ${text(input.source, 'source')}, ${text(input.externalClickId, 'externalClickId', false)}, ${money(input.attributedRevenue, 'attributedRevenue', Number(order[0].total))})`); await prisma.$executeRaw(Prisma.sql`INSERT INTO audit_logs (id, workspace_id, user_id, action, entity_type, entity_id, after_json, request_reference) VALUES (${randomUUID()}, ${workspaceId}, ${auth.userId}, 'order.attribution.create', 'AttributionRecord', ${id}, ${JSON.stringify({ orderId, campaignId })}::jsonb, ${requestId})`); const rows = await prisma.$queryRaw<Array<Record<string, unknown>>>(Prisma.sql`SELECT * FROM attribution_records WHERE id = ${id}`); return serialize(rows[0]); }
