import type { Ad, AdInput, AdSet, AdSetInput, ApiError, Audience, AudienceInput, AuthMeResponse, AuthResponse, Campaign, CampaignAnalytics, CampaignInput, CreativeFatigueSignal, HealthResponse, PerformanceDiagnosis, PerformanceSnapshot, PerformanceSnapshotInput, Product, ProductInput, ProductVariant, ProductVariantInput } from '@adsgenius/shared-types';

export interface ApiClientOptions { baseUrl: string; fetchImpl?: typeof fetch; }
export class ApiClientError extends Error { readonly payload: ApiError; readonly status: number; constructor(status: number, payload: ApiError) { super(payload.error.message); this.name = 'ApiClientError'; this.status = status; this.payload = payload; } }
export class ApiClient {
  private readonly baseUrl: string; private readonly fetchImpl: typeof fetch;
  constructor(options: ApiClientOptions) { this.baseUrl = options.baseUrl.replace(/\/$/, ''); this.fetchImpl = options.fetchImpl ?? fetch; }
  private async request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await this.fetchImpl(`${this.baseUrl}${path}`, { ...init, credentials: 'include', headers: { 'content-type': 'application/json', ...(init.headers ?? {}) } }); const body = response.status === 204 ? undefined : await response.json(); if (!response.ok) throw new ApiClientError(response.status, body as ApiError); return body as T; }
  async health(): Promise<HealthResponse> { return this.request<HealthResponse>('/api/v1/health'); }
  async register(input: { email: string; password: string; name: string; workspaceName: string }): Promise<AuthResponse> { return this.request<AuthResponse>('/api/v1/auth/register', { method: 'POST', body: JSON.stringify(input) }); }
  async login(email: string, password: string): Promise<AuthResponse> { return this.request<AuthResponse>('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); }
  async refresh(): Promise<AuthResponse['tokens']> { return this.request<AuthResponse['tokens']>('/api/v1/auth/refresh', { method: 'POST' }); }
  async logout(): Promise<void> { await this.request('/api/v1/auth/logout', { method: 'POST' }); }
  async me(): Promise<AuthMeResponse> { return this.request<AuthMeResponse>('/api/v1/auth/me'); }
  async listProducts(workspaceId: string, search?: string): Promise<Product[]> { const query = search?.trim() ? `?search=${encodeURIComponent(search.trim())}` : ''; return (await this.request<{ data: Product[] }>(`/api/v1/workspaces/${workspaceId}/products${query}`)).data; }
  async getProduct(workspaceId: string, productId: string): Promise<Product> { return this.request<Product>(`/api/v1/workspaces/${workspaceId}/products/${productId}`); }
  async createProduct(workspaceId: string, input: ProductInput): Promise<Product> { return this.request<Product>(`/api/v1/workspaces/${workspaceId}/products`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateProduct(workspaceId: string, productId: string, input: Partial<ProductInput>): Promise<Product> { return this.request<Product>(`/api/v1/workspaces/${workspaceId}/products/${productId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteProduct(workspaceId: string, productId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/products/${productId}`, { method: 'DELETE' }); }
  async createVariant(workspaceId: string, productId: string, input: ProductVariantInput): Promise<ProductVariant> { return this.request<ProductVariant>(`/api/v1/workspaces/${workspaceId}/products/${productId}/variants`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateVariant(workspaceId: string, productId: string, variantId: string, input: Partial<ProductVariantInput>): Promise<ProductVariant> { return this.request<ProductVariant>(`/api/v1/workspaces/${workspaceId}/products/${productId}/variants/${variantId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteVariant(workspaceId: string, productId: string, variantId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/products/${productId}/variants/${variantId}`, { method: 'DELETE' }); }
  async listCreatives(workspaceId: string): Promise<Array<{ id: string; name: string; angle: string | null; versions: Array<{ id: string; version: number }>; copies: Array<{ id: string; primaryText: string | null; headline: string | null; cta: string | null }> }>> { return (await this.request<{ data: Array<{ id: string; name: string; angle: string | null; versions: Array<{ id: string; version: number }>; copies: Array<{ id: string; primaryText: string | null; headline: string | null; cta: string | null }> }> }>(`/api/v1/workspaces/${workspaceId}/creatives`)).data; }
  async listAudiences(workspaceId: string): Promise<Audience[]> { return (await this.request<{ data: Audience[] }>(`/api/v1/workspaces/${workspaceId}/audiences`)).data; }
  async getAudience(workspaceId: string, audienceId: string): Promise<Audience> { return this.request<Audience>(`/api/v1/workspaces/${workspaceId}/audiences/${audienceId}`); }
  async createAudience(workspaceId: string, input: AudienceInput): Promise<Audience> { return this.request<Audience>(`/api/v1/workspaces/${workspaceId}/audiences`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateAudience(workspaceId: string, audienceId: string, input: Partial<AudienceInput>): Promise<Audience> { return this.request<Audience>(`/api/v1/workspaces/${workspaceId}/audiences/${audienceId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteAudience(workspaceId: string, audienceId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/audiences/${audienceId}`, { method: 'DELETE' }); }
  async listCampaigns(workspaceId: string): Promise<Campaign[]> { return (await this.request<{ data: Campaign[] }>(`/api/v1/workspaces/${workspaceId}/campaigns`)).data; }
  async getCampaign(workspaceId: string, campaignId: string): Promise<Campaign> { return this.request<Campaign>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}`); }
  async createCampaign(workspaceId: string, input: CampaignInput): Promise<Campaign> { return this.request<Campaign>(`/api/v1/workspaces/${workspaceId}/campaigns`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateCampaign(workspaceId: string, campaignId: string, input: Partial<CampaignInput>): Promise<Campaign> { return this.request<Campaign>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteCampaign(workspaceId: string, campaignId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}`, { method: 'DELETE' }); }
  async listAdSets(workspaceId: string, campaignId: string): Promise<AdSet[]> { return (await this.request<{ data: AdSet[] }>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets`)).data; }
  async createAdSet(workspaceId: string, campaignId: string, input: AdSetInput): Promise<AdSet> { return this.request<AdSet>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateAdSet(workspaceId: string, campaignId: string, adSetId: string, input: Partial<AdSetInput>): Promise<AdSet> { return this.request<AdSet>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteAdSet(workspaceId: string, campaignId: string, adSetId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}`, { method: 'DELETE' }); }
  async listAds(workspaceId: string, campaignId: string, adSetId: string): Promise<Ad[]> { return (await this.request<{ data: Ad[] }>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}/ads`)).data; }
  async createAd(workspaceId: string, campaignId: string, adSetId: string, input: AdInput): Promise<Ad> { return this.request<Ad>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}/ads`, { method: 'POST', body: JSON.stringify(input) }); }
  async updateAd(workspaceId: string, campaignId: string, adSetId: string, adId: string, input: Partial<AdInput>): Promise<Ad> { return this.request<Ad>(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}/ads/${adId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
  async deleteAd(workspaceId: string, campaignId: string, adSetId: string, adId: string): Promise<void> { await this.request(`/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/adsets/${adSetId}/ads/${adId}`, { method: 'DELETE' }); }
  async ingestPerformanceSnapshot(workspaceId: string, input: PerformanceSnapshotInput): Promise<PerformanceSnapshot> { return this.request<PerformanceSnapshot>(`/api/v1/workspaces/${workspaceId}/analytics/snapshots`, { method: 'POST', body: JSON.stringify(input) }); }
  async getCampaignAnalytics(workspaceId: string, campaignId: string, start?: string, end?: string): Promise<CampaignAnalytics> { const params = new URLSearchParams(); if (start) params.set('start', start); if (end) params.set('end', end); const suffix = params.toString() ? `?${params.toString()}` : ''; return this.request<CampaignAnalytics>(`/api/v1/workspaces/${workspaceId}/analytics/campaigns/${campaignId}${suffix}`); }
  async diagnoseCampaign(workspaceId: string, campaignId: string, input: { start?: string; end?: string } = {}): Promise<PerformanceDiagnosis> { return this.request<PerformanceDiagnosis>(`/api/v1/workspaces/${workspaceId}/analytics/campaigns/${campaignId}/diagnose`, { method: 'POST', body: JSON.stringify(input) }); }
  async listDiagnostics(workspaceId: string, campaignId?: string): Promise<PerformanceDiagnosis[]> { const query = campaignId ? `?campaignId=${encodeURIComponent(campaignId)}` : ''; return (await this.request<{ data: PerformanceDiagnosis[] }>(`/api/v1/workspaces/${workspaceId}/analytics/diagnostics${query}`)).data; }
  async listCreativeFatigue(workspaceId: string): Promise<CreativeFatigueSignal[]> { return (await this.request<{ data: CreativeFatigueSignal[] }>(`/api/v1/workspaces/${workspaceId}/analytics/creative-fatigue`)).data; }
  async detectCreativeFatigue(workspaceId: string, creativeVersionId: string): Promise<CreativeFatigueSignal> { return this.request<CreativeFatigueSignal>(`/api/v1/workspaces/${workspaceId}/analytics/creative-fatigue/${creativeVersionId}`, { method: 'POST' }); }
}
